import { db } from "@/db";
import { creations } from "@/db/schema";
import { desc, eq } from "drizzle-orm";
import { Users, Sparkles, Heart, Share2, Search, ArrowUpRight } from "lucide-react";
import Link from "next/link";
import { formatDate } from "@/lib/utils";

export const dynamic = "force-dynamic";

/**
 * Community Creations Hub (Server Component)
 * 
 * Public Feed:
 * Sabhi users dwara publicly share kiye gaye articles aur images yahan display hote hain.
 * Phase 4 me isme 1-Click "Remix Prompt" button connect hoga.
 */
export default async function CommunityPage() {
  // Fetch all published creations
  const publicCreations = await db.query.creations.findMany({
    where: eq(creations.publish, true),
    orderBy: [desc(creations.createdAt)],
    limit: 20,
  });

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
      {/* Community Header */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 pb-6 border-b border-border/40">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-300 border border-emerald-500/30 text-xs font-semibold mb-2">
            <Users className="w-3.5 h-3.5" />
            Phase 4 Community Hub
          </div>
          <h1 className="text-3xl font-extrabold text-white">Community Creations Feed</h1>
          <p className="text-muted-foreground text-sm mt-1">
            Discover prompts and high-performing articles generated by creators worldwide.
          </p>
        </div>

        <Link
          href="/studio/article"
          className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white text-sm font-semibold shadow-lg shadow-indigo-600/20 transition-all"
        >
          Create & Share
        </Link>
      </div>

      {/* Community Feed Grid */}
      {publicCreations.length === 0 ? (
        <div className="glass-panel rounded-2xl p-12 text-center flex flex-col items-center max-w-lg mx-auto">
          <div className="w-14 h-14 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 mb-4">
            <Sparkles className="w-7 h-7" />
          </div>
          <h3 className="text-base font-bold text-white">No Public Creations Yet</h3>
          <p className="text-xs text-muted-foreground mt-1 text-center">
            Be the first to publish an article or AI image to the community hub!
          </p>
          <Link
            href="/dashboard"
            className="mt-5 px-4 py-2 rounded-lg bg-secondary hover:bg-secondary/80 text-white text-xs font-medium border border-border"
          >
            Go to Studios
          </Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {publicCreations.map((item) => (
            <div
              key={item.id}
              className="glass-card rounded-2xl p-6 flex flex-col justify-between group hover:border-indigo-500/40"
            >
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[11px] uppercase tracking-wider font-semibold px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-400 border border-indigo-500/30">
                    {item.type}
                  </span>
                  <span className="text-xs text-muted-foreground">
                    {formatDate(item.createdAt)}
                  </span>
                </div>

                <h3 className="text-base font-bold text-white group-hover:text-indigo-300 transition-colors line-clamp-1">
                  {item.title}
                </h3>

                <p className="text-xs text-muted-foreground mt-2 line-clamp-3 leading-relaxed">
                  {item.prompt}
                </p>
              </div>

              <div className="mt-6 pt-4 border-t border-border/40 flex items-center justify-between">
                <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                  <Heart className="w-3.5 h-3.5 text-pink-500 fill-pink-500" />
                  <span>{item.likes?.length || item.likesCount || 0}</span>
                </div>

                <button className="text-xs font-semibold text-indigo-400 hover:text-indigo-300 flex items-center gap-1">
                  1-Click Remix &rarr;
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
